/** Canonical themeable tokens. Every theme must define all of these. */
export const REQUIRED_TOKENS = [
  "--app-primary",
  "--app-on-primary",
  "--app-secondary",
  "--app-on-secondary",
  "--app-bg",
  "--app-surface",
  "--app-surface-raised",
  "--app-on-surface",
  "--app-on-surface-muted",
  "--app-success",
  "--app-on-success",
  "--app-error",
  "--app-on-error",
  "--app-accent-teal",
  "--app-border",
  "--app-focus-ring",
  "--app-radius-sm",
  "--app-radius-md",
  "--app-radius-lg",
  "--app-radius-full",
  "--app-shadow-sm",
  "--app-shadow-md",
  "--app-shadow-button",
  "--app-font-display",
  "--app-font-body",
  "--app-font-thai",
] as const;
